name: Vérification d'une pull-request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Exécution des tests unitaires
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Installation des dépendances
        run: npm install

      - name: Exécution des tests
        run: npm test

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: test  # Ne s'exécute que si les tests réussissent

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner
